version: "3.9"

services:
  html-converter:
    build:
      context: ./
      dockerfile: ./HtmlConverter/Dockerfile 
    image: empty/html-converter
    ports: 
      - "5001:5001"   
    volumes:
      - ./HtmlConverter/Data:/Data
      - ${APPDATA}/ASP.NET/https:/root/.aspnet/https
    environment:
      - ASPNETCORE_URLS=https://0.0.0.0:5001 
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/root/.aspnet/https/htmlconverter.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=test
      - Settings__ClientUrl=https://localhost:5003
      - Settings__ConversionServiceUrl=http://nginx:5050
      - Settings__ConnectionString=Data Source=/Data/jobs.db
    cpus: 1.0
    mem_reservation: 512m

  conversionservice1:
    build:
      context: ./
      dockerfile: ./HtmlConverter.ConversionService/Dockerfile  
    image: empty/html-converter-conversion-service
    expose: 
      - "5002" 
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:5002
    cpus: 1.0
    mem_reservation: 512m

  conversionservice2:
    build:
      context: ./
      dockerfile: ./HtmlConverter.ConversionService/Dockerfile  
    image: empty/html-converter-conversion-service
    expose: 
      - "5005" 
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:5005
    cpus: 1.0
    mem_reservation: 512m
     
  html-converter-client:
    build:
      context: ./
      dockerfile: ./HtmlConverter.Client/Dockerfile  
    image: empty/html-converter-client
    ports: 
      - "5003:5003" 
    volumes:
      - ${APPDATA}/ASP.NET/https:/root/.aspnet/https
    cpus: 1.0
    mem_reservation: 512m

  nginx:
    container_name: nginx
    image: nginx  
    volumes:
      - ./Deployment/config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - conversionservice1
      - conversionservice2
    ports:
      - "5050:5050"      
                 
networks:
  default:
    driver: bridge
    name: petstore