// <auto-generated />
using System;
using HtmlConverter.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HtmlConverter.Migrations
{
    [DbContext(typeof(ConversionJobsContext))]
    [Migration("20221006030338_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.9");

            modelBuilder.Entity("HtmlConverter.Data.Entities.ConversionJob", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT")
                        .HasColumnName("created");

                    b.Property<DateTime?>("Finished")
                        .HasColumnType("TEXT")
                        .HasColumnName("finished");

                    b.Property<string>("HtmlContents")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("html_contents");

                    b.Property<string>("HtmlFileName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("html_file_name");

                    b.Property<byte[]>("PdfContents")
                        .HasColumnType("BLOB")
                        .HasColumnName("pdf_contents");

                    b.Property<int?>("Status")
                        .HasColumnType("INTEGER")
                        .HasColumnName("status");

                    b.HasKey("ID")
                        .HasName("pk_jobs");

                    b.ToTable("jobs", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
